// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGHfVo_eU85Tnmy1WusGtgAl_JbgYgDeY',
    appId: '1:716985107592:web:d691e0152f7fbd09d20b3d',
    messagingSenderId: '716985107592',
    projectId: 'allgotur',
    authDomain: 'allgotur.firebaseapp.com',
    storageBucket: 'allgotur.appspot.com',
    measurementId: 'G-RM46RYHT1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEgQ0qnSyemUIuo7A4KM4-fxUUrjPsZnk',
    appId: '1:716985107592:android:312ee3d12d86beacd20b3d',
    messagingSenderId: '716985107592',
    projectId: 'allgotur',
    storageBucket: 'allgotur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD88cLRL9LnOQw2wgbTy_bgQ75au4ZOkIw',
    appId: '1:716985107592:ios:d02215ceab5a71f0d20b3d',
    messagingSenderId: '716985107592',
    projectId: 'allgotur',
    storageBucket: 'allgotur.appspot.com',
    iosBundleId: 'com.example.googleBootcamp60',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD88cLRL9LnOQw2wgbTy_bgQ75au4ZOkIw',
    appId: '1:716985107592:ios:d02215ceab5a71f0d20b3d',
    messagingSenderId: '716985107592',
    projectId: 'allgotur',
    storageBucket: 'allgotur.appspot.com',
    iosBundleId: 'com.example.googleBootcamp60',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGHfVo_eU85Tnmy1WusGtgAl_JbgYgDeY',
    appId: '1:716985107592:web:af69bc7ca2cf8de3d20b3d',
    messagingSenderId: '716985107592',
    projectId: 'allgotur',
    authDomain: 'allgotur.firebaseapp.com',
    storageBucket: 'allgotur.appspot.com',
    measurementId: 'G-WFTNHSDG9N',
  );
}
